apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
data:
  JWT_ISSUER: https://localhost:7054/
  JWT_AUDIENCE: https://localhost:7054/
  NEW_RELIC_BASE_URL: https://insights-collector.newrelic.com/v1/accounts
  ENVIRONMENT: Production
