apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert-container
          image: andersonsrocha/alert:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: RabbitMQ__HostName
              value: "rabbitmq.messaging.svc.cluster.local"
            - name: RabbitMQ__QueueName
              value: "alert.queue"
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: alert-config
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: alert-config
                  key: JWT_AUDIENCE
            - name: ServiceClients__NewRelic__BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: alert-config
                  key: NEW_RELIC_BASE_URL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: alert-config
                  key: ENVIRONMENT

            - name: ConnectionStrings__MongoConnection
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: connectionstring
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: jwtkey
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: newrelickey
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
            - name: Services
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: services
            - name: ServiceClients__NewRelic__AccountId
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: accountid
            - name: ServiceClients__NewRelic__ApiKey
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: apikey
